### ISSUE TITLE
Qbank Usage Reporting error

### ISSUE THREAD

**Issue by oneweb-admin** [superbigco/craft-qbankconnector#2]
Not sure what this means, but I'm getting a log of errors for "Qbank Usage Reporting"
![QUR](https://user-images.githubusercontent.com/48016183/60507539-ac52a380-9cc8-11e9-85de-00ae81c030d6.PNG)

**Comment by sjelfull** [comment]
This usually happens when the credentials is wrong. Could you check the logs for any errors?
